from random import sample

file_path = "Votes.xml"
counter=0
with open(file_path, "r", encoding="utf-8") as file:
    for i, line in enumerate(file):
        counter+=1
        if i >= 40:  # Stop after 100 lines
            break
        print(line.strip())  # Remove trailing whitespace
    print(counter)

# 59819051  posts
# 22484238  users
# 90380326  comments
# 238984014  votes


# posts sample
# <row Id="38779" PostTypeId="1" AcceptedAnswerId="40472" CreationDate="2008-09-02T03:41:06.880" Score="6" ViewCount="6282" Body="&lt;p&gt;I have a wcf application hosted in a windows service running a local windows account. Do I need to set an SPN for this account? If so, what's the protocol the SPN needs to be set under? I know how to do this for services over HTTP, but have never done it for net.tcp.&lt;/p&gt;&#xA;" OwnerUserId="781" OwnerDisplayName="Esteban" LastEditorUserId="1116" LastEditorDisplayName="John Nolan" LastEditDate="2008-09-02T08:49:19.323" LastActivityDate="2013-06-24T17:03:55.833" Title="What SPN do I need to set for a net.tcp service?" Tags="|wcf|security|spn|" AnswerCount="2" CommentCount="0" FavoriteCount="0" ContentLicense="CC BY-SA 2.5" />
# <row Id="38781" PostTypeId="2" ParentId="23930" CreationDate="2008-09-02T03:44:26.013" Score="3" Body="&lt;p&gt;Agda 2: Functional, dependently typed.&lt;/p&gt;&#xA;&#xA;&lt;pre&gt;&lt;code&gt;data Nat = zero | suc (m::Nat)&#xA;&#xA;add (m::Nat) (n::Nat) :: Nat&#xA; = case m of&#xA;     (zero ) -&amp;gt; n&#xA;     (suc p) -&amp;gt; suc (add p n)&#xA;&#xA;mul (m::Nat) (n::Nat)::Nat&#xA;   = case m of&#xA;      (zero ) -&amp;gt; zero&#xA;      (suc p) -&amp;gt; add n (mul p n)&#xA;&#xA;factorial (n::Nat)::Nat &#xA; = case n of&#xA;    (zero ) -&amp;gt; suc zero&#xA;    (suc p) -&amp;gt; mul n (factorial p)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;" OwnerUserId="3434" LastEditorUserId="3434" LastEditorDisplayName="Apocalisp" LastEditDate="2008-09-18T22:09:07.470" LastActivityDate="2008-09-18T22:09:07.470" CommentCount="0" CommunityOwnedDate="2008-09-19T07:14:59.840" ContentLicense="CC BY-SA 2.5" />
# <row Id="38784" PostTypeId="1" AcceptedAnswerId="41285" CreationDate="2008-09-02T03:49:17.920" Score="7" ViewCount="3474" Body="&lt;p&gt;I use &lt;strong&gt;Delphi&lt;/strong&gt; for many years, and although I have now moved on to Visual Studio I still fondly remember numbered bookmarks (&lt;kbd&gt;CTRL&lt;/kbd&gt;+&lt;kbd&gt;K&lt;/kbd&gt;+&lt;kbd&gt;1&lt;/kbd&gt; to set bookmark 1, &lt;kbd&gt;CTRL&lt;/kbd&gt;+&lt;kbd&gt;Q&lt;/kbd&gt;+&lt;kbd&gt;1&lt;/kbd&gt; to goto bookmark 1).&lt;/p&gt;&#xA;&#xA;&lt;p&gt;Is there a &lt;strong&gt;Visual Studio&lt;/strong&gt; equivalent? I'm find the dumb bookmarks in VS a chore after Delphi. I want to bookmark then return to a specific place in the file.&lt;/p&gt;&#xA;" OwnerUserId="4149" LastEditorUserId="4779472" LastEditDate="2015-06-27T14:21:16.453" LastActivityDate="2021-11-25T10:14:44.487" Title="Visual Studio equivalent to Delphi bookmarks" Tags="|visual-studio|delphi|brief-bookmarks|" AnswerCount="8" CommentCount="1" FavoriteCount="0" ContentLicense="CC BY-SA 3.0" />
# <row Id="38785" PostTypeId="2" ParentId="38784" CreationDate="2008-09-02T03:54:14.587" Score="4" Body="&lt;p&gt;&lt;kbd&gt;Ctrl&lt;/kbd&gt; &lt;kbd&gt;K&lt;/kbd&gt; + &lt;kbd&gt;Ctrl&lt;/kbd&gt; &lt;kbd&gt;K&lt;/kbd&gt; - Add/Remove Bookmark on Line&lt;br /&gt;&#xA;&lt;kbd&gt;Ctrl&lt;/kbd&gt; &lt;kbd&gt;K&lt;/kbd&gt; + &lt;kbd&gt;Ctrl&lt;/kbd&gt; &lt;kbd&gt;N&lt;/kbd&gt; - Go to Next Bookmark&lt;br /&gt;&#xA;&lt;kbd&gt;Ctrl&lt;/kbd&gt; &lt;kbd&gt;K&lt;/kbd&gt; + &lt;kbd&gt;Ctrl&lt;/kbd&gt; &lt;kbd&gt;P&lt;/kbd&gt; - Go to Previous Bookmark&lt;/p&gt;&#xA;&lt;p&gt;There are other options as well. Look under Edit-&amp;gt;Bookmarks menu,&lt;/p&gt;&#xA;" OwnerUserId="380" OwnerDisplayName="Vaibhav" LastEditorUserId="9454010" LastEditDate="2021-06-15T02:11:14.180" LastActivityDate="2021-06-15T02:11:14.180" CommentCount="1" ContentLicense="CC BY-SA 4.0" />
# <row Id="38787" PostTypeId="2" ParentId="38769" CreationDate="2008-09-02T03:58:41.830" Score="3" Body="&lt;p&gt;MPP does have its own object model that can be used to access data in it. The info should be available here: &lt;a href=&quot;http://msdn.microsoft.com/en-us/office/aa905469.aspx&quot; rel=&quot;nofollow noreferrer&quot;&gt;http://msdn.microsoft.com/en-us/office/aa905469.aspx&lt;/a&gt;&lt;/p&gt;&#xA;" OwnerUserId="380" OwnerDisplayName="Vaibhav" LastActivityDate="2008-09-02T03:58:41.830" CommentCount="0" ContentLicense="CC BY-SA 2.5" />
# <row Id="38789" PostTypeId="1" AcceptedAnswerId="38792" CreationDate="2008-09-02T03:59:44.417" Score="4" ViewCount="4406" Body="&lt;p&gt;I have a &lt;code&gt;web-service&lt;/code&gt; that I will be deploying to dev, staging and production. Along with this will be an &lt;strong&gt;ASP.net&lt;/strong&gt; application that will be deploying separately but also in those three stages. &lt;/p&gt;&#xA;&#xA;&lt;p&gt;What is the most pragmatic way to change the following line in the web-service to match the current environment?&lt;/p&gt;&#xA;&#xA;&lt;pre&gt;&lt;code&gt;[WebService(Namespace = &quot;http://dev.mycompany.com/MyAppsWebService&quot;)]&#xA;[WebService(Namespace = &quot;http://stage.mycompany.com/MyAppsWebService&quot;)]&#xA;[WebService(Namespace = &quot;http://mycompany.com/MyAppsWebService&quot;)]&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;" OwnerUserId="3149" OwnerDisplayName="Kevin Lamb" LastEditorUserId="5423108" LastEditDate="2017-07-04T08:48:45.030" LastActivityDate="2017-07-04T08:48:45.030" Title="Web Service Namespace Dynamic Naming" Tags="|c#|asp.net|web-services|" AnswerCount="1" CommentCount="0" ContentLicense="CC BY-SA 3.0" />
# <row Id="38791" PostTypeId="1" AcceptedAnswerId="38793" CreationDate="2008-09-02T04:01:09.827" Score="4" ViewCount="2483" Body="&lt;p&gt;Which Database table Schema is more efficient and why?&lt;/p&gt;&#xA;&#xA;&lt;pre&gt;&lt;code&gt;&quot;Users (UserID, UserName, CompamyId)&quot;&#xA;&quot;Companies (CompamyId, CompanyName)&quot;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&#xA;&lt;p&gt;OR&lt;/p&gt;&#xA;&#xA;&lt;pre&gt;&lt;code&gt;&quot;Users (UserID, UserName)&quot;&#xA;&quot;Companies (CompamyId, CompanyName)&quot;&#xA;&quot;UserCompanies (UserID, CompamyId)&quot;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&#xA;&lt;p&gt;Given the fact that user and company have one-to-one relation.&lt;/p&gt;&#xA;" OwnerUserId="191" OwnerDisplayName="Ramesh Soni" LastActivityDate="2008-09-17T13:44:01.717" Title="Which database table Schema is more efficient?" Tags="|database-design|" AnswerCount="6" CommentCount="1" ContentLicense="CC BY-SA 2.5" />



# users sample
# <row Id="-1002" Reputation="1" CreationDate="2021-05-12T18:16:42.380" DisplayName="Google Cloud" LastAccessDate="2021-05-12T18:16:42.380" AboutMe="&lt;p&gt;A collective for developers who utilize Google Cloud’s infrastructure and platform capabilities. This collective is organized and managed by the Stack Overflow community.&lt;/p&gt;&#xA;" Views="0" UpVotes="0" DownVotes="0" />
# <row Id="-1" Reputation="1" CreationDate="2008-07-31T00:00:00.000" DisplayName="Community" LastAccessDate="2008-08-26T00:16:53.810" WebsiteUrl="https://meta.stackexchange.com" Location="on the server farm" AboutMe="&lt;p&gt;Hi, I'm not really a person.&lt;/p&gt;&#xA;&lt;p&gt;I'm a background process that helps keep this site clean!&lt;/p&gt;&#xA;&lt;p&gt;I do things like&lt;/p&gt;&#xA;&lt;ul&gt;&#xA;  &lt;li&gt;Randomly poke old unanswered questions every hour so they get some attention&lt;/li&gt;&#xA;  &lt;li&gt;Own community questions and answers so nobody gets unnecessary reputation from them&lt;/li&gt;&#xA;  &lt;li&gt;Own downvotes on spam/evil posts that get permanently deleted&lt;/li&gt;&#xA;  &lt;li&gt;Own suggested edits from anonymous users&lt;/li&gt;&#xA;  &lt;li&gt;&lt;a href=&quot;https://meta.stackexchange.com/a/92006&quot;&gt;Remove abandoned questions&lt;/a&gt;&lt;/li&gt;&#xA;&lt;/ul&gt;&#xA;" Views="168428" UpVotes="0" DownVotes="0" AccountId="-1" />
# <row Id="1" Reputation="63708" CreationDate="2008-07-31T14:22:31.287" DisplayName="Jeff Atwood" LastAccessDate="2024-02-17T00:51:04.657" WebsiteUrl="https://blog.codinghorror.com/" Location="El Cerrito, CA" AboutMe="&lt;p&gt;&lt;a href=&quot;https://blog.codinghorror.com/stack-overflow-none-of-us-is-as-dumb-as-all-of-us/&quot; rel=&quot;nofollow noreferrer&quot;&gt;Stack Overflow Valued Associate #00001&lt;/a&gt;&lt;/p&gt;&#xA;&lt;p&gt;Wondering how our software development process works? &lt;a href=&quot;https://www.youtube.com/watch?v=qM4zMofsI7w&quot; rel=&quot;nofollow noreferrer&quot;&gt;Take a look!&lt;/a&gt;&lt;/p&gt;&#xA;&lt;p&gt;Find me &lt;a href=&quot;https://twitter.com/codinghorror&quot; rel=&quot;nofollow noreferrer&quot;&gt;on twitter&lt;/a&gt;, or &lt;a href=&quot;https://blog.codinghorror.com/&quot; rel=&quot;nofollow noreferrer&quot;&gt;read my blog&lt;/a&gt;. Don't say I didn't warn you &lt;em&gt;because I totally did&lt;/em&gt;.&lt;/p&gt;&#xA;&lt;p&gt;However, &lt;a href=&quot;https://blog.codinghorror.com/farewell-stack-exchange/&quot; rel=&quot;nofollow noreferrer&quot;&gt;I no longer work at Stack Exchange, Inc&lt;/a&gt;. I'll miss you all. Well, &lt;em&gt;some&lt;/em&gt; of you, anyway. :)&lt;/p&gt;&#xA;" Views="596583" UpVotes="3270" DownVotes="1108" AccountId="1" />
# <row Id="2" Reputation="6156" CreationDate="2008-07-31T14:22:31.287" DisplayName="Geoff Dalgas" LastAccessDate="2024-03-31T23:16:02.157" WebsiteUrl="http://stackoverflow.com" Location="Corvallis, OR" AboutMe="&lt;p&gt;Dev #2 who helped create Stack Overflow currently working at Microsoft. I love all people willing to share their knowledge. Without community we are nothing.&lt;/p&gt;&#xA;&lt;p&gt;Find me on:&lt;/p&gt;&#xA;&lt;p&gt;&lt;a href=&quot;http://www.twitter.com/SuperDalgas&quot; rel=&quot;nofollow noreferrer&quot;&gt;Twitter&lt;/a&gt;&#xA;&lt;br&gt;&lt;br&gt;&#xA;&lt;a href=&quot;http://blog.stackoverflow.com/2009/05/welcome-stack-overflow-valued-associate-00003/&quot;&gt;Stack Overflow Valued Associate #00003&lt;/a&gt;&lt;/p&gt;&#xA;" Views="32951" UpVotes="657" DownVotes="78" AccountId="2" />
# <row Id="3" Reputation="15767" CreationDate="2008-07-31T14:22:31.287" DisplayName="Jarrod Dixon" LastAccessDate="2023-04-29T21:17:53.580" WebsiteUrl="http://jarroddixon.com" Location="Johnson City, TN, USA" AboutMe="&lt;p&gt;Former &lt;a href=&quot;http://blog.stackoverflow.com/2009/01/welcome-stack-overflow-valued-associate-00002/&quot;&gt;Developer on the Stack Overflow team&lt;/a&gt;.&lt;/p&gt;&#xA;&lt;p&gt;Was dubbed &lt;strong&gt;SALTY SAILOR&lt;/strong&gt; by Jeff Atwood, as filth and flarn would oft-times fly when dealing with a particularly nasty bug!&lt;/p&gt;&#xA;&lt;ul&gt;&#xA;&lt;li&gt;Twitter me: &lt;a href=&quot;http://twitter.com/jarrod_dixon&quot; rel=&quot;nofollow noreferrer&quot;&gt;jarrod_dixon&lt;/a&gt;&lt;/li&gt;&#xA;&lt;li&gt;Email me: jarrod.m.dixon@gmail.com&lt;/li&gt;&#xA;&lt;/ul&gt;&#xA;" Views="30431" UpVotes="7765" DownVotes="91" AccountId="3" />
# <row Id="4" Reputation="33554" CreationDate="2008-07-31T14:22:31.317" DisplayName="Joel Spolsky" LastAccessDate="2024-04-06T16:22:08.870" WebsiteUrl="https://joelonsoftware.com/" Location="New York, NY" AboutMe="&lt;p&gt;In 2000 I co-founded Fog Creek Software, where we created lots of cool things like the &lt;a href=&quot;https://fogbugz.com&quot; rel=&quot;nofollow noreferrer&quot;&gt;FogBugz bug tracker&lt;/a&gt;, &lt;a href=&quot;https://trello.com&quot; rel=&quot;nofollow noreferrer&quot;&gt;Trello&lt;/a&gt;, and &lt;a href=&quot;https://glitch.com&quot; rel=&quot;nofollow noreferrer&quot;&gt;Glitch&lt;/a&gt;. I also worked with &lt;a href=&quot;https://stackoverflow.com/users/1/jeff-atwood&quot;&gt;Jeff Atwood&lt;/a&gt; to create &lt;a href=&quot;https://stackoverflow.com&quot;&gt;Stack Overflow&lt;/a&gt; and served as CEO of Stack Overflow from 2010-2019.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;Today I serve as the chairman of the board for Stack Overflow, Glitch, and &lt;a href=&quot;https://hash.ai&quot; rel=&quot;nofollow noreferrer&quot;&gt;HASH&lt;/a&gt;.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;I served as a paratrooper in the Israeli army, graduated from Yale University in 1991, and spent time on the Excel team at Microsoft where I was the program manager responsible for the launch of VBA in Excel 5.0. I’ve also written four books, do a lot of Arduino stuff, and talk too much about Barry’s Bootcamp and Burning Man.&lt;/p&gt;&#xA;" Views="84765" UpVotes="827" DownVotes="88" AccountId="4" />
# <row Id="5" Reputation="52637" CreationDate="2008-07-31T14:22:31.317" DisplayName="Jon Galloway" LastAccessDate="2023-03-07T02:39:34.550" WebsiteUrl="http://weblogs.asp.net/jgalloway/" Location="San Diego, CA" AboutMe="&lt;p&gt;Technical Evangelist at Microsoft, specializing in ASP.NET MVC.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;I don't use this site anymore because the moderators close or delete far too many of the useful questions.&lt;/p&gt;&#xA;" Views="15464" UpVotes="759" DownVotes="26" AccountId="5" />


# votes sample
# <row Id="14967360" PostId="8440" VoteTypeId="2" CreationDate="2011-05-12T00:00:00.000" />
# <row Id="14969494" PostId="8440" VoteTypeId="2" CreationDate="2011-05-12T00:00:00.000" />
# <row Id="15032293" PostId="8440" VoteTypeId="2" CreationDate="2011-05-14T00:00:00.000" />
# <row Id="15062845" PostId="8440" VoteTypeId="2" CreationDate="2011-05-16T00:00:00.000" />
# <row Id="15350663" PostId="8440" VoteTypeId="2" CreationDate="2011-05-25T00:00:00.000" />
# <row Id="15433520" PostId="8440" VoteTypeId="2" CreationDate="2011-05-27T00:00:00.000" />

#comments sample
# <row Id="24342921" PostId="4" Score="20" Text="Also, Decimal can't represent as wide a value as a Double. Decimal can only go up to +/-7.9228162514264337593543950335E+28; whereas a Double can go up to +/-1.79769313486232E+308" CreationDate="2008-09-21T04:09:42.507" UserId="18658" />
# <row Id="117303571" PostId="4" Score="4" Text="@TraumaPony it's a `trackbar`. It is unlikely that it has ever been done to use such a high value on `trackbar`" CreationDate="2021-02-24T13:07:37.333" UserId="2748412" />
# <row Id="119523765" PostId="4" Score="7" Text="I was always told it is better to multiply by 0.0002 than divide by 5000." CreationDate="2021-05-20T13:17:54.800" UserId="42552" />
# <row Id="129582146" PostId="4" Score="1" Text="*&quot;trans&quot;* is probably for *&quot;[transparency](https://en.wiktionary.org/wiki/transparency#Noun)&quot;* (from [an answer](https://stackoverflow.com/questions/4/how-do-i-convert-a-decimal-to-a-double-in-c/7#7)?), the opposite of [opacity](https://en.wiktionary.org/wiki/opacity#Noun), indicated by the variable name *&quot;Opacity&quot;*." CreationDate="2022-08-16T15:03:40.723" UserId="63550" />
# <row Id="137929248" PostId="4" Score="0" Text="First question of stackoverflow...." CreationDate="2024-03-28T08:05:56.640" UserId="2743206" />
